version: "3.2"
services:
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
      - ./api-gateaway/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - registro
      
  registro:
    volumes:
      - ./registro/:/mnt/
    build: ./registro
    working_dir: /backend/
    command: sh run.sh 

