version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data

  worker:
    volumes:
      - ./registro/:/mnt/
    build: ./registro
    working_dir: /backend/
    command: rq worker -u 'redis://redis/0'
    depends_on:
      - redis
      
  nginx:
    image: nginx:latest
    ports:
      - 5002:80
    volumes:
      - ./api-gateway/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - registro

  monitor:
    volumes:
      - ./monitor/:/mnt/
      - /var/run/docker.sock:/var/run/docker.sock
    build: ./monitor
    working_dir: /backend/
    command: sh startup.sh
    depends_on:
      - redis
      - registro

  registro:
    volumes:
      - ./registro/:/mnt/
    build: ./registro
    working_dir: /backend/
    command: sh run.sh 
    depends_on:
      - redis
