version: "3.2"
services:
  redis:
    image: redis
    volumes:
      - ./data:/data

  nginx:
    image: nginx:latest
    ports:
      - 5002:80
    volumes:
      - ./api-gateway/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - registro1
      - registro2
      - autorizador1
      - orquestador

  monitor:
    container_name: monitor
    volumes:
      - ./monitor/:/mnt/
      - /var/run/docker.sock:/var/run/docker.sock
    build: ./monitor
    working_dir: /backend/
    command: sh startup.sh
    depends_on:
      - redis
      - registro1
      - registro2
      - orquestador

  autorizador1:
    container_name: autorizador1
    volumes:
      - ./autorizador/:/mnt/
    build: ./autorizador
    working_dir: /backend/
    command: sh startup.sh        
    depends_on:
      - registro1
      - registro2

  registro1:
    container_name: registro1
    volumes:
      - ./registro/:/mnt/
    build: ./registro
    working_dir: /backend/
    command: sh run-ins-1.sh
    depends_on:
      - redis

  registro2:
    container_name: registro2
    volumes:
      - ./registro/:/mnt/
    build: ./registro
    working_dir: /backend/
    command: sh run-ins-2.sh
    depends_on:
      - redis

  orquestador:
    container_name: orquestador
    volumes:
      - ./orquestador/:/mnt/
    build: ./orquestador
    working_dir: /backend/
    command: sh run.sh
    depends_on:
      - redis
      - registro1
      - registro2
      - autorizador1
